### PR TITLE
Add cmake features

### PR DESCRIPTION
**Pull request by Nava2**
Adds support for many `cmake` features: 
- `cpp11_lang/auto_type`
- `cpp11_lang/default_function_template_args`
- `cpp11_lang/lambdas`
- `cpp11_lang/parameter_pack`
- `cpp11_lang/range_for`
- `cpp11_lang/right_angle_brackets`
- `cpp11_lang/strong_enum`

### CODE REVIEW

**Comment by foonathan** [comment]
Thank you for the pull.

I originally didn't include some of those features like auto and lambdas because they are imho purely syntax features and can be avoided easily. But thanks for doing the work, I appreciate it!

The check is failing because you have changed `_comp_handle_feature()` to a function in 93ffcd172c0e9829914b15b623d43ead3ece23b2, please revert that again.

**Comment by Nava2** [comment]
Sorry, I'll get to this tomorrow. 

I also have another branch which fixed this, but has "logging" put in place to calm down the spam, [add-log-levels](https://github.com/Nava2/compatibility/tree/add-log-levels). It's not polished enough for a PR, but it includes this branch and fixes it ([Travis Build](https://travis-ci.org/Nava2/compatibility/builds/154654211)). 

If you like the output/logging of this branch, I can clean this one up instead and do it in two parts.

**Comment by foonathan** [comment]
I'm interested in the logging changes as well, but please fix this issue before so that I can merge this PR and update the readme.

**Comment by Nava2** [comment]
Sure, I fixed the problem last night and I'll rebase and apply it on this branch.

**Comment by Nava2** [comment]
Okay, I've fixed the macro generation by cherry-picking some commits from the other branch. The headers are now defined in an internal macro: `_COMP_HEADERS` instead of the generic `headers` variable which collided in my scripts (and would likely hit others!).

**Comment by foonathan** [comment]
Oh, didn't realize that the headers variable was public, my mistake.

You have a copy-paste error for cpp11_lang/strong_enum.cmake, the feature name is auto_type.
(BTW: I'd prefer the name cpp11_lang/enum_class, I think it is more intuitive)

**Comment by Nava2** [comment]
Fixed the typo and changed the name. Have to leave the cmake var with strong_enums because, well, that's what CMake chose!

**Comment by foonathan** [comment]
Yeah, sure but the compatibility names don't need to be the same.

I'll merge now and then I'll take a look at the other PR.

**Pull request merged**
